//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.13 at 09:25:21 PM IDT 
//


package GameUtilV2;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ECN-Dictionary-File" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element ref="{}ECN-Board"/>
 *         &lt;element ref="{}ECN-Teams"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ecnDictionaryFile",
    "ecnBoard",
    "ecnTeams"
})
@XmlRootElement(name = "ECN-Game")
public class ECNGame {

    // Changed from V1
    @XmlElement(name = "ECN-Dictionary-File", required = true)
    protected Object ecnDictionaryFile;

    // Same as V1
    @XmlElement(name = "ECN-Board", required = true)
    protected ECNBoard ecnBoard;

    // Changed from V1
    @XmlElement(name = "ECN-Teams", required = true)
    protected ECNTeams ecnTeams;

    // Added since V1
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the ecnDictionaryFile property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getECNDictionaryFile() {
        return ecnDictionaryFile;
    }

    /**
     * Sets the value of the ecnDictionaryFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setECNDictionaryFile(Object value) {
        this.ecnDictionaryFile = value;
    }

    /**
     * Gets the value of the ecnBoard property.
     * 
     * @return
     *     possible object is
     *     {@link ECNBoard }
     *     
     */
    public ECNBoard getECNBoard() {
        return ecnBoard;
    }

    /**
     * Sets the value of the ecnBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECNBoard }
     *     
     */
    public void setECNBoard(ECNBoard value) {
        this.ecnBoard = value;
    }

    /**
     * Gets the value of the ecnTeams property.
     * 
     * @return
     *     possible object is
     *     {@link ECNTeams }
     *     
     */
    public ECNTeams getECNTeams() {
        return ecnTeams;
    }

    /**
     * Sets the value of the ecnTeams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECNTeams }
     *     
     */
    public void setECNTeams(ECNTeams value) {
        this.ecnTeams = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
