//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.13 at 09:25:21 PM IDT 
//


package GameUtilV2;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ECN-Team" maxOccurs="6"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ecnTeam"
})
@XmlRootElement(name = "ECN-Teams")
public class ECNTeams {

    @XmlElement(name = "ECN-Team", required = true)
    protected List<ECNTeam> ecnTeam;

    /**
     * Gets the value of the ecnTeam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ecnTeam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getECNTeam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ECNTeam }
     * 
     * 
     */
    public List<ECNTeam> getECNTeam() {
        if (ecnTeam == null) {
            ecnTeam = new ArrayList<ECNTeam>();
        }
        return this.ecnTeam;
    }

}
