//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.13 at 09:25:21 PM IDT 
//


package GameUtilV2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ECNTeam }
     * 
     */
    public ECNTeam createECNTeam() {
        return new ECNTeam();
    }

    /**
     * Create an instance of {@link ECNTeams }
     * 
     */
    public ECNTeams createECNTeams() {
        return new ECNTeams();
    }

    /**
     * Create an instance of {@link ECNGame }
     * 
     */
    public ECNGame createECNGame() {
        return new ECNGame();
    }

    /**
     * Create an instance of {@link ECNBoard }
     * 
     */
    public ECNBoard createECNBoard() {
        return new ECNBoard();
    }

    /**
     * Create an instance of {@link ECNLayout }
     * 
     */
    public ECNLayout createECNLayout() {
        return new ECNLayout();
    }

}
